site_name: gdalcubes
site_url: https://github.com/appelmar/gdalcubes
repo_url: https://github.com/appelmar/gdalcubes
site_author: Marius Appel
nav:
    - Home: index.md
    - Getting started: R.md
    - Basic concepts: concepts.md
    - R package: R.md
    - C++ API: cpp-api.md
    - Server API: server-api.md

theme:
  name: 'material'
use_directory_urls: false